# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

strategy:
  maxParallel: 1

steps:
- script: |
    echo "Running single job"
  displayName: 'Run single job'
  timeoutInMinutes: 30


